version: "3.7"

services:
  api-v1:
    container_name: api-v1
    environment:
      NODE_ENV: dev
    build: .
    volumes:
      - .:/api-v1
    ports:
      - 3000:3000
    command: [ "npm", "run", "start" ]
